### ISSUE TITLE
How to use vim-indent-guides in my vim profiles?

### ISSUE THREAD

**Issue by CaoPeng** [nathanaelkane/vim-indent-guides#105]
I had copied 
**indent_guides.vim** --> .vim/autoload/
**color_helper.vim** --> .vim/autoload/

**indent_guides.vim** -->.vim/plugin

This function does not work!

How can I  configure my **.vimrc**?

**Comment by nathanaelkane** [comment]
The guides are off by default, try toggling them on with either `<Leader>ig` (default mapping), or `:IndentGuidesToggle`.
