### ISSUE TITLE
Error while processing function <SNR>13

### ISSUE THREAD

**Issue by rianby64** [nathanaelkane/vim-indent-guides#108]
This is the message that I got after press <LEADER>ig

```
Error detected while processing function <SNR>13_IndentGuidesToggle..indent_guides#toggle..indent_guides#enable..indent_guide
s#init_script_vars..indent_guides#capture_highlight:
line    2:
E411: highlight group not found: Normal
```

The .vimrc file that I've is:

``` vim
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'jelera/vim-javascript-syntax'
Plugin 'nathanaelkane/vim-indent-guides'

call vundle#end()            " required
filetype plugin indent on    " required

set smarttab
set expandtab
set number
set tabstop=2
set shiftwidth=2
set softtabstop=2

set pastetoggle=<F2>

set incsearch
set hlsearch

set title
set visualbell

set background=dark

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

```

And the file that I'm processing is

``` javascript
'use strict';
// A comment
feature('Manipulating Dimension', function() {

  scenario('Setup information to render', function() {

    given('a <dimension> directive', function() { });

    when('I put name attribute as "a name"', function() { });

    then('I\'ve an HTML definition that contains "a name"', function() { });
  });

});
```

Can't understand what's going wrong.
Thanks a million in advance

**Comment by MintPaw** [comment]
I'm having the same problem with a slightly different error message.
``Error detected while processing function <SNR>24_IndentGuidesEnable[1]..indent_guides#enable[8]..indent_guides#init_script_vars[7]..indent...
``

It only happens when I open some files, I have no idea why either.

**Comment by hexchain** [comment]
Same issue, using https://github.com/nathanaelkane/vim-indent-guides/issues/31#issuecomment-4583981 as solution now.

**Comment by nathanaelkane** [comment]
Sounds like you're not using a colorscheme, or your colorscheme isn't defining colours for the Normal highlight group.

Try using a different colorscheme, or manually defining the indent guide colours:

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

Please re-open if this is not the case.

**Comment by rianby64** [comment]
Thanks a lot! Works to me! :+1:

**Comment by Whainte** [comment]
can I modify the autoload scripts to make it load another highlight group other than Normal?

**Comment by nathanaelkane** [comment]
@Whainte there's currently no config option to change it from `Normal`.

**Comment by Whainte** [comment]
Cant I edit the vim script to make it read another highlighting group like Conceal or?
and btw it mysteriously worked after manually load colorscheme default

**Comment by nathanaelkane** [comment]
It should work if you edit the local autoload file.

**Comment by soylens** [comment]
Yeah, iirc it generated a Normal when i added an explicit "colorscheme default" to the global vimrc.
However i ended up changing another colorscheme which also worked pretty well

**Comment by yzsatgithub** [comment]
these lines didn't work for me:
```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

the same error occurred.   Why is that?  @nathanaelkane 
thank you

**Comment by nathanaelkane** [comment]
@yzsatgithub have you tried defining a colorscheme? i.e. `colorscheme default`

**Comment by yzsatgithub** [comment]
> @yzsatgithub have you tried defining a colorscheme? e.g. `colorscheme default`

@nathanaelkane  No I didn't. But I do have a setting line `color vc` for syntax highlighting. Is this the same as what you asked?

**Comment by nathanaelkane** [comment]
@yzsatgithub yep, it's all the same `:colo[rscheme]` command.

If you're still getting the `highlight group not found: Normal` error, it means the `Normal` highlight group hasn't been defined before the Indent Guides plugin initialises. It could be that your plugin doesn't define `Normal`. Maybe try defining it manually, i.e. `hi Normal guibg=black`
