### ISSUE TITLE
[OSX][neovim] Weird behaviour with 'set cursorline'

### ISSUE THREAD

**Issue by t0str** [nathanaelkane/vim-indent-guides#111]
I really like to highlight the current line, but this plugin gives weird behaviour in this case:

![screen shot 2016-03-22 at 13 45 38](https://cloud.githubusercontent.com/assets/231959/13952121/e41e6590-f034-11e5-8f51-f6a4971176f6.png)

There are two rectangles that are bg-colored, but should be cursorline-colored. Maybe disable your plugin for the current line if cursorline is set?

Settings:
```
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
let g:indent_guides_enable_on_vim_startup=1
```

Thank you for a great plugin!

Cheers,
t0str

**Comment by nathanaelkane** [comment]
I believe you can fix this by defining the following highlight:

```
hi IndentGuidesOdd ctermbg=NONE guibg=NONE
```

This clears the background colour on every 2nd guide, which is the guide that's overriding your `cursorline`.

**Comment by t0str** [comment]
Thank you very much, issue solved :)
