### ISSUE TITLE
Do not work with vim-less and vim-slim plugins

### ISSUE THREAD

**Issue by peancored** [nathanaelkane/vim-indent-guides#112]
I've installed [vim-slim](https://github.com/slim-template/vim-slim) and [vim-less](https://github.com/groenewege/vim-less) plugins, and there are indent guides everywhere, except files with .slim and .less extension. Here's my .vimrc file, I am autoloading your plugin in that way:

```
autocmd VimEnter * IndentGuidesEnable
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  ctermbg=236 guibg=#202020
hi IndentGuidesEven ctermbg=238 guibg=#333333  
filetype plugin indent on
filetype plugin on
```

also i've tried to put this lines in ~/.vim/after/plugins/something.vim, but it didn't work.

`let g:indent_guides_enable_on_vim_startup = 1` also doesn't solve problem.

But it works if I call :IndentGuidesEnable while editing .slim file.

**Comment by reubano** [comment]
same thing for me with `jade` and `styl` files. `: IndentGuidesEnable` works, but as soon as you navigate to a new buffer and back, the guides are gone again.

**Comment by Toshegg** [comment]
@reubano, you should use neovim instead. Everything works perfectly in neovim.

**Comment by reubano** [comment]
Thanks, i'll check it out!
