### ISSUE TITLE
Error with no colorscheme

### ISSUE THREAD

**Issue by CMCDragonkai** [nathanaelkane/vim-indent-guides#113]
Without a colorscheme setting, I get this upon running `,ig`:

```
Error detected while processing function <SNR>13_IndentGuidesToggle[1]..indent_guides#toggle[4]..indent_guides#enable[8]..indent_guides#init_script_vars[7]..i
ndent_guides#capture_highlight:
line    2:
E411: highlight group not found: Normal
```

**Comment by nathanaelkane** [comment]
Sounds like you're not using a colorscheme, or your colorscheme isn't defining colours for the Normal highlight group.

Try using a different colorscheme, or manually defining the indent guide colours:

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

Please re-open if this is not the case.
