### ISSUE TITLE
Automatically reset guides on shiftwidth change

### ISSUE THREAD

**Issue by harendra-kumar** [nathanaelkane/vim-indent-guides#116]
Different files may have different indentation levels and often times one has to manually set the shiftwidth to match the style of the file. It will be nice if guides can change automatically as soon as the shiftwidth is set.

Currently I toggle guides twice to reflect the change after setting shiftwidth.

**Comment by Coacher** [comment]
Add `autocmd OptionSet * call indent_guides#process_autocmds()` to your .vimrc.

**Comment by harendra-kumar** [comment]
Thanks! My vim does not seem to have OptionSet, will try a newer version of vim. But it seems this should work.

**Comment by Coacher** [comment]
You need vim >= 7.4.786

**Comment by nathanaelkane** [comment]
Thanks @Coacher that's handy to know, might add that in a future version.
