### ISSUE TITLE
vim-indent-guides  can't auto-work on haml file

### ISSUE THREAD

**Issue by clay-f** [nathanaelkane/vim-indent-guides#117]
i was open the haml file the 'vim-indent-guides' can't work, but i manual click menu syntax > haml
and then will be work, but when i switch another buffer and then back to haml file ,the 'vim-indent-guides' can't work again, must be click haml syntax again, it's would be workd.
  how does solve it ?

vim version: 8.0.94

**Comment by nathanaelkane** [comment]
So is it only with haml files that you're having an issue? No other file types?

Upon opening a haml file, before changing the syntax in the menu, what does the following command output? `:echo &filetype`

Does adding the following to your `.vimrc` file fix the issue? `autocmd BufRead,BufNewFile *.haml set ft=haml`

**Comment by clay-f** [comment]
oh, yes

1. open .rb file the plugin work fine.
2. `echo &filetype` show haml
3. `autocmd BufRead,BufNewFile *.haml set ft=haml` add .vimrc seem make no sense

**Comment by nathanaelkane** [comment]
> `autocmd BufRead,BufNewFile *.haml set ft=haml` add .vimrc seem make no sense

This command is basically automating the steps you were taking manually to get the indent guides working with haml files. This is a potential work-around, put it in your vimrc and let me know how it goes.

**Comment by clay-f** [comment]
no, add above config , can't work too,

**Comment by clay-f** [comment]
![Uploading Screen Shot 2016-12-06 at 11.39.10.png…](index.html.haml)

**Comment by nathanaelkane** [comment]
Can you please try the following: `autocmd FileType haml :IndentGuidesEnable`

Again, this is just a work-around. I suspect another plugin is causing the indent guide highlight groups to be cleared.

**Comment by clay-f** [comment]
oh, not work yet.

**Comment by clay-f** [comment]
OK, found the issue:

plugin conflict ?

   `Plugin 'gorodinskiy/vim-coloresque'`

thanks

**Comment by nathanaelkane** [comment]
Nice :)

**Comment by nathanaelkane** [comment]
I was able to reproduce the problem on my end with `gorodinskiy/vim-coloresque`. At some point I'll try to sort this out, but it's possible that the problem is in their repo.

**Comment by clay-f** [comment]
i think that so , ha ha, may their repo problem.
