### ISSUE TITLE
Unable to set the colors manually

### ISSUE THREAD

**Issue by ezmiller** [nathanaelkane/vim-indent-guides#118]
Hi, nice plugin. I've been trying to modify the default colors to make things a bit more subtle. I've had no luck though. Here's what I tried:

```
" Settings for nathanael/vim-indent-guides
:set background=dark
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=black   ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=darkslategrey ctermbg=4
```

The result looks like this: 
![](https://s3.amazonaws.com/ezmiller/public/images/nvim_Python_2016-12-27_15-26-26.png)

Clearly, not the colors I tried to dictate! I'm wondering if the problem might have something to do with the fact that I'm using nvim within the context of ITerm2. Any suggestions anyone?

**Comment by nathanaelkane** [comment]
Are you by any chance using a custom iTerm 2 theme? If so, then you only have 16 colors to choose from when using the `cterm` highlight groups.

NeoVim supports truecolor, so maybe try to find an alternative version of your colorscheme that sets the `gui` highlight groups.

**Comment by nathanaelkane** [comment]
Closing issue as problem is not related to indent guides.
