### ISSUE TITLE
How can I use the papercolor theme?

### ISSUE THREAD

**Issue by gatlinnewhouse** [nathanaelkane/vim-indent-guides#119]
https://github.com/NLKNguyen/papercolor-theme

I want the colors to match this theme (which they are not). Is there a way to fix this or even set the colors manually in my vimrc?

**Comment by nathanaelkane** [comment]
I just installed the colorscheme on NeoVim and the colours look correct to me.

If you want to set custom indent colours, check out [this section of the readme](https://github.com/nathanaelkane/vim-indent-guides#setting-custom-indent-colors).
