### ISSUE TITLE
Vundle support

### ISSUE THREAD

**Issue by IVXCVI** [nathanaelkane/vim-indent-guides#123]
Any hope of seeing this plugin support the Vundle installation method?

**Comment by nathanaelkane** [comment]
I use Vundle for Vim and vim-plug for NeoVim, and both work fine.

Do you just mean that I should mention it in the docs? In which case you're probably right.

**Comment by IVXCVI** [comment]
I had just tried adding it with Vundle under Macvim, and it didn't seem to work. I thought it would have worked. I'll try it again tomorrow and see if I missed anything.

On March 29, 2017 1:08:01 AM CDT, Nate Kane <notifications@github.com> wrote:
>I use Vundle for Vim and vim-plug for NeoVim, and both work fine.
>
>Do you just mean that I should mention it in the docs? In which case
>you're probably right.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nathanaelkane/vim-indent-guides/issues/123#issuecomment-289992317

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nathanaelkane** [comment]
The documentation has been updated with Vundle installation details.
