### ISSUE TITLE
indent don't work with text file

### ISSUE THREAD

**Issue by aaryabhatt** [nathanaelkane/vim-indent-guides#124]
Hi,

I am able to run indent with below setting with .haml filetype

let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=4
autocmd FileType haml :IndentGuidesEnable

but when I try to declare text file or perl filetype than it did not work, is there a way that I can declare it for 
every file i open on ubuntu.

--
Thanks
Amit Bondwal

**Comment by aaryabhatt** [comment]
solved it 
my current working code with color scheme is 

```
colorscheme badwolf
set ts=1 sw=1 et
let g:indent_guides_auto_colors = 0
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
let g:indent_guides_color_change_percent = 3
let g:indent_guides_enable_on_vim_startup = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=236
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237
```

**Comment by aaryabhatt** [comment]
it solved

**Comment by nathanaelkane** [comment]
Glad to hear it, thanks for the update. :)
