### ISSUE TITLE
Documentation for Enabling, Disabling, Toggling Plugin

### ISSUE THREAD

**Issue by T99-** [nathanaelkane/vim-indent-guides#127]
I'm sure many people would find it useful if you added documentation for the fairly important commands:
```
:IndentGuidesToggle
:IndentGuidesEnable
:IndentGuidesDisable
```
It's always nice to be able to read the documentation (readme, wiki) than have to go digging through the code!

**Comment by nathanaelkane** [comment]
Agreed, thanks for the PR :)
