### ISSUE TITLE
E411: highlight group not found: Normal

### ISSUE THREAD

**Issue by vectra-tme** [nathanaelkane/vim-indent-guides#131]
I am getting the following error:

```
Error detected while processing function <SNR>43_IndentGuidesToggle[1]..indent_guides#toggle[4]..indent_guides#enable[8]..indent_guides#init_    script_vars[7]..indent_guides#capture_highlight:
line    2:
 E411: highlight group not found: Normal  
```

I found several previous bugs that discuss color scheme workarounds so I added the following to .vimrc
```
 let g:indent_guides_auto_colors = 0
 hi IndentGuidesOdd  guibg=red   ctermbg=3
 hi IndentGuidesEven guibg=green ctermbg=4 
```

**Comment by tylermolamphy** [comment]
I am seeing the same, but only when opening vim via the terminal command alone, and landing at the welcome page." If I launch vim with any file as an argument, (or by calling -c and opening a vimwiki as I usually do,) I do not see the reported error. 

The behavior started when I set `let g:indent_guides_enable_on_vim_startup = 1`.

**Comment by ianpan870102** [comment]
Having the same issue here, but everytime I press <Enter> to continue, it seems all right. I wonder if I can simply disable the promt.

**Comment by nathanaelkane** [comment]
That's correct @ianpan870102, thanks for commenting.

Usually this happens when a colorscheme hasn't been explicitly set, or your colorscheme doesn't define colours for the Normal highlight group.
