### ISSUE TITLE
Disable Guides for Terminal Buffers

### ISSUE THREAD

**Issue by atomdmac** [nathanaelkane/vim-indent-guides#140]
I use `ranger.vim` with my setup and it looks like `vim-indent-guides` applies indent guides in `ranger` windows as well as normal buffers.  Is there a way to disable `vim-indent-guides` for buffers that contain terminal applications?

# Example
See the gray bars in the lower left.
![image](https://user-images.githubusercontent.com/1461736/65069431-acbe1a80-d958-11e9-8479-8bdde02a32a3.png)

**Comment by nathanaelkane** [comment]
Try using the `indent_guides_exclude_filetypes` option and see if that works, e.g. `let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']`

**Comment by nathanaelkane** [comment]
Alternatively, would this work?

```vim
if !has("gui")
  let g:indent_guides_enable_on_vim_startup = 0
endif
```

**Comment by atomdmac** [comment]
@nathanaelkane Thanks for the suggestions!  I've tried the `exclude_filetypes` option but either it doesn't work or I'm just using the correct file type.  (I've tried `terminal` and `ranger` as values).

I'm using the terminal version of VIM so I'm not sure if the `!has("gui")` check will work (as I believe it will always return `true` in my case).

**Comment by atomdmac** [comment]
Update:  This isn't a perfect solution as it operates on _all_ terminal buffers but it seems to work well enough for my use case:
```vim
au TermEnter * IndentGuidesDisable
au TermLeave * IndentGuidesEnable
```

If anyone knows how to narrow this down a bit more (ex. _just_ to terminals containing `ranger` instances) that'd be pretty neat.  Otherwise, this solution is probably good enough for me.

Closing this for now but please feel free to re-open if a better solution arises.
