### ISSUE TITLE
Error detected <SNR>27 after updating Plugins today

### ISSUE THREAD

**Issue by andrewpritchett** [nathanaelkane/vim-indent-guides#141]
Error detected while processing function <SNR>27_IndentGuidesEnable[1]..indent_guides#enable[8]..indent_guides#init_script_vars[7]..indent_guides#capture_highlight:
line    2:
E411: highlight group not found: Normal

Installed and updated via Vundle
VIM version 8.0.1365
MacOS 10.14.6

**Comment by nathanaelkane** [comment]
Sounds like you're not using a colorscheme, or your colorscheme isn't defining colours for the Normal highlight group.

Try using a different colorscheme, or manually defining the indent guide colours:

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

Please re-open if this is not the case.
