### ISSUE TITLE
Destroys performance in terminal in neovim only

### ISSUE THREAD

**Issue by unphased** [nathanaelkane/vim-indent-guides#145]
fzf is a critical part of my workflow and I've found lately in neovim that it is due to rendering these indent guides all over the empty space in the terminal that makes fzf super sluggish. regular vim does not do this.

I'd like to ask if anyone knows the cause of why this plugin triggers inside the neovim terminal, and how to stop it, because I would really like to use neovim, this plugin, and fzf, together.

neovim:

![image](https://user-images.githubusercontent.com/1542910/95927060-cdd78180-0d8b-11eb-8e5d-b3089c7b8ae2.png)

vim:

![image](https://user-images.githubusercontent.com/1542910/95927099-e5166f00-0d8b-11eb-9e69-5344f8aa5b24.png)

**Comment by unphased** [comment]
I hope that the autocommand workaround posted in #140 will work for this.

**Comment by unphased** [comment]
It totally works. Yes!!!

**Comment by ypid** [comment]
Is there still an issue here or can it be closed?

**Comment by unphased** [comment]
I'll close, since the workaround is satisfactory and it's not clear that the indent guides are necessarily doing anything bad.
