### ISSUE TITLE
How can I set the indent line thinner?

### ISSUE THREAD

**Issue by themysteryboy** [nathanaelkane/vim-indent-guides#148]
My tab is 2 and the indent line will look very crowded and I want to set it thinner, my size set now is 1

**Comment by nathanaelkane** [comment]
`let g:indent_guides_guide_size = 1` is the thinnest that this plugin can go. If you want thinner and you're using NeoVim, I would suggest https://github.com/lukas-reineke/indent-blankline.nvim, which can use  a character as the indent guide, e.g. `|`.
