### ISSUE TITLE
spaces not recognized until 8 characters, then treated as tabs

### ISSUE THREAD

**Issue by wxl** [nathanaelkane/vim-indent-guides#17]
I got my MacVim tweaked just the way I wanted on the Intel/Snow Leopard desktop. Decided to do the same thing to the PPC/Leopard laptop. So I copy .gvimrc and install my only plugin, indent guides. The end result: spaces are ignored until repeated 8 times, at which point it is color-coded like a tab (though navigation in vim still treats the whole "block" like a space and not a tab). Up until that point, there is no color coding.

Unfortunately, I can't say much about the CLI interface. <code>:IndentGuidesToggle</code> yields:

<pre><code>Error detected while processing function<SNR>3_IndentGuidesToggle..indent_guides#enable..indent_guides#init_script_vars..indent_guides#capture_highlight:
line    2:
E411: highlight group not found: Normal</code></pre>

Appropriate <code>:let</code>s--

<pre><code>indent_guides_color_name_guibg_pattern  guibg='\?\zs[0-9A-Za-z ]\+\ze'\?
loaded_indent_guides  #1
indent_guides_color_hex_guibg_pattern  guibg=\zs#[0-9A-Fa-f]\{6\}\ze
indent_guides_auto_colors #0
indent_guides_start_level #1
indent_guides_color_hex_pattern  #[0-9A-Fa-f]\{6\}
indent_guides_enable_on_vim_startup #0
indent_guides_color_change_percent #10
indent_guides_indent_levels #30
indent_guides_autocmds_enabled #0
indent_guides_debug   #0
indent_guides_guide_size #0
w:indent_guides_matches []</code></pre>

here's some relevant bits from <code>:highlight</code> including the supposedly missing group:

<pre><code>Normal         xxx guifg=Grey50 guibg=black
IndentGuidesOdd xxx guibg=darkblue
IndentGuidesEven xxx guibg=darkgreen</code></pre>

all of which suggests to me that everything's in order. Harumph?

**Comment by nathanaelkane** [comment]
Sounds like you're not using a colorscheme, or your colorscheme isn't defining colours for the Normal highlight group.

Try using a different colorscheme, or manually defining the indent guide colours:

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

Please re-open if this is not the case.
