### ISSUE TITLE
shiftwidth=0 does not work

### ISSUE THREAD

**Issue by jotrk** [nathanaelkane/vim-indent-guides#57]
Hello,

setting `shiftwidth=0` (it's supposed to use the tabstop value then) breaks the plugin. The foreground of the very first column is then in a different color which looks kind of strange and is unreadable (for me) because it is almost the same color as the background.

I've replaced `set sw=0` with `let &shiftwidth=&tabstop` in my `.vimrc` and now it works again. However, I'm wondering why it won't work the `sw=0` option as the help page (for sw) says.

**Comment by nathanaelkane** [comment]
I was able to replicate locally - the associated PR has been (manually) merged.
