### ISSUE TITLE
Using with NeoVim - Support?

### ISSUE THREAD

**Issue by jthomas** [nathanaelkane/vim-indent-guides#81]
I've installed the plugin using vim-plug in NeoVim. There plugin doesn't appear to have started opening a sample file and running the <Leader>ig command gives the following error:

Error detected while processing function <SNR>57_IndentGuidesToggle..indent_guides#toggle..indent_gui
des#enable..indent_guides#init_script_vars..indent_guides#capture_highlight:
line    2:
E411: highlight group not found: Normal

Is there an issue with my setup?

**Comment by jthomas** [comment]
Fixed adding the following to my vim file:
colorscheme default

**Comment by nathanaelkane** [comment]
Was going to suggest that :)

In GUI mode, the colors for the indent guides are all derived from the Normal highlight group.
