### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by jrean** [nathanaelkane/vim-indent-guides#82]
Hi,

How to get indent-guides on empty lines?

```
if(true) {
    $var = "foo";
// empty line
    $foo = "var";
}
```

**Comment by nathanaelkane** [comment]
I'm afraid this is not possible, see issue #23 for details.

**Comment by jrean** [comment]
Thank you @nathanaelkane. I read it but as it was dated from Aug 27, 2011, I thought maybe something has been done. (In php we have a lot of empty lines..)

**Comment by ChrisHonniball** [comment]
I have it working but you have to get VIM to not remove the empty space on a new line. To do this you have to trick VIM into not removing the trailing space by putting *something other than a space* on the line before leaving insert mode. See my [vimrc](https://github.com/ChrisHonniball/vim-settings/blob/master/vimrc#L22) on how I did it.

**Comment by jrean** [comment]
Thank you very much @ChrisHonniball, it does the trick and works well :)

**Comment by nathanaelkane** [comment]
> I have it working but you have to get VIM to not remove the empty space on a new line.

Sounds like a reasonable work-around if you don't mind the unneeded spaces on "empty" lines.

**Comment by jrean** [comment]
Yes of course.
But now the main issue is that my “Trailing white spaces” detection is on fire :p
