### ISSUE TITLE
dont work with neovim

### ISSUE THREAD

**Issue by alex93ushakov** [nathanaelkane/vim-indent-guides#86]
Linux Mint 17, neovim was installed through ppa, vim-indent-guides works don't work.
How to fix it?

**Comment by simonweil** [comment]
I'm running on OSX with neovim and vim-indent-guides for months and all is fine.
Did you try to disable all other plugins and settings to see if it's related to some other plugin or setting?

**Comment by alex93ushakov** [comment]
I remove .nvim folder and .nvimrc, hade made clear install, and tabed columns dont highlights.

**Comment by simonweil** [comment]
I'm no n/vim expert, try opening a bug in neovim, they are very responsive.

**Comment by alex93ushakov** [comment]
On usual vim in gnome terminal don't work too.

**Comment by BriceSD** [comment]
Works well for me on archlinux / urxvt with neovim version : 
NVIM 0.0.0-alpha+201506061429
Commit: 6609a545ad2f56e83af3dde06e66da6c3b9a747a

**Comment by alex93ushakov** [comment]
https://github.com/nathanaelkane/vim-indent-guides/issues/92

**Comment by nathanaelkane** [comment]
If it's the same as #92, try the following:

Sounds like you're not using a colorscheme, or your colorscheme isn't defining colours for the Normal highlight group.

Try using a different colorscheme, or manually defining the indent guide colours:

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

Please re-open if this is not the case.
