### ISSUE TITLE
[Feature] Add option to provide git/hg/svn/etc path manually

### ISSUE THREAD

**Issue by rafaelnp** [nathanaelkane/vim-indent-guides#87]
This option would be useful when working on windows or working on environments where custom paths are used. It would add a great flexibility.

**Comment by nathanaelkane** [comment]
This plugin shouldn't need to know anything about git/hg/svn, was this issue intended for a different GitHub repo?

**Comment by rafaelnp** [comment]
The plug-in complain when a VCS or a diff tool is not found. What would you suggest as an alternative solution?

**Comment by nathanaelkane** [comment]
What sort of error are you getting? No VCS or diff tool is required for this plugin.

**Comment by rafaelnp** [comment]
Hello @nathanaelkane,

My apollogies, I open the issue in the wrong project. My mistake, the vim-indent-guides works very well here, I am sorry for wasting your time. I shall pay more attention next time. I am closing the issue right now.

**Comment by nathanaelkane** [comment]
No worries @rafaelnp, no problem at all :)
