### ISSUE TITLE
mac don't show indent guide

### ISSUE THREAD

**Issue by zouqilin** [nathanaelkane/vim-indent-guides#89]

**Comment by nathanaelkane** [comment]
Please provide more information. I use MacVIM and both the terminal and GUI version should work with indent guides.

I need to know what version of Vim, term/GUI, what colorscheme, etc. A link to your config and the colorscheme you're using would also help.

**Comment by zouqilin** [comment]
~/Code/test/ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  5 2014 21:00:28)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses

and here is  vimrc i used
https://github.com/amix/vimrc

**Comment by DeepikaNR** [comment]
I am using vim 7.3. Getting the following error:
![screen shot 2015-06-23 at 9 56 22 pm](https://cloud.githubusercontent.com/assets/11847739/8311403/9d9f0f2e-19f3-11e5-8bc8-7a71d0675837.png)

**Comment by nathanaelkane** [comment]
Looks like you're either not using a colorscheme, or your colorscheme isn't defining colours for the Normal highlight group.

Try using a different colorscheme, or manually defining the indent guide colours:

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

Please re-open if this is not the case.
