### ISSUE TITLE
Continue highlighting over empty lines.

### ISSUE THREAD

**Issue by tomprince** [nathanaelkane/vim-indent-guides#90]
If a line is empty, and indent-guides are shown above and below, the guides should be shown on the empty line as well.

For code with many empty lines, the breaks in the indent-guides are distracting.

**Comment by rightaway** [comment]
+1

**Comment by liuyang1** [comment]
+1, and it seems not easy, as there is non-character.

**Comment by nathanaelkane** [comment]
This is an I'm afraid this is not possible, see issue #23 for details.
