### ISSUE TITLE
neovim - plugin show error after IndentGuideEnable

### ISSUE THREAD

**Issue by alex93ushakov** [nathanaelkane/vim-indent-guides#92]
```
Error detected while processing function <SNR>12_IndentGuidesEnable..indent_guid
es#enable..indent_guides#init_script_vars..indent_guides#capture_highlight:
line    2:
E411: highlight group not found: Normal
```

**Comment by nathanaelkane** [comment]
Sounds like you're not using a colorscheme, or your colorscheme isn't defining colours for the Normal highlight group.

Try using a different colorscheme, or manually defining the indent guide colours:

```
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=red   ctermbg=3
hi IndentGuidesEven guibg=green ctermbg=4
```

Please re-open if this is not the case.

**Comment by alex93ushakov** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/9713207/8398331/a0c9f774-1df2-11e5-8b85-09427d432dc2.png)
