### ISSUE TITLE
Cannot install on OSX

### ISSUE THREAD

**Issue by spawnazzo** [nathanaelkane/vim-indent-guides#95]
Hi guys, 
I have MacVim Custom Version 7.4 (76) i installed awesome vimrc and tried to get vim-indent-guides works with no success. 

Then i tried to remove awesome vimrc installed pathogen cloned the repo into the bundle directory neither the help is working.

Any hint

**Comment by yukie-** [comment]
hey spawnazzo, did you ever get vim-indent working?

**Comment by spawnazzo** [comment]
On my current setup nope previously yes.

**Comment by yukie-** [comment]
when you removed awesome vimrc did you create a new .vimrc? What did you put in your .vimrc?

sorry about the difficulties! I'm on OS X 10.10.3, using Vundle instead of Pathogen, but was able to get it installed. have you tried using Vundle?

**Comment by spawnazzo** [comment]
Of course i created another .vimrc ;) and i put just what was written in the Readme. The problem is that in my other mac works fine, in my company ones it does not. 

I'll try to use bundle and let you know

**Comment by spawnazzo** [comment]
Installed vundle and did a :PluginList the plugin is not listed (but is present in the bundle folder of course)

**Comment by yukie-** [comment]
nice! and yah haha I figured you did just had to ask :b

with Vundle in your .vimrc double check your run time path 

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
 
Plugin 'nathanaelkane/vim-indent-guides'

call vundle#end()

then load up vim and run :PluginInstall

and you should be good!! in vim you can :IndentGuidesEnabled and then you should see them :) 

let me know if this works. gl!

**Comment by spawnazzo** [comment]
ok so 
```
set nocompatible              " be iMproved, required

filetype off                  " required

syn on
set nu

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'nathanaelkane/vim-indent-guides'

colorscheme bclear
set ts=2 sw=2 et
let g:indent_guides_start_level=2

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
```
cannot see any indent line what's missing?

![screen shot 2015-07-23 at 11 16 29](https://cloud.githubusercontent.com/assets/1212510/8847139/4b86826c-312c-11e5-8c06-06e5b0a3f7aa.png)

**Comment by yukie-** [comment]
okay so 

colorscheme bclear
set ts=2 sw=2 et
let g:indent_guides_start_level_2

needs to go *after* 

call vundle#end() 

look at the last line of your .vimrc: " " Put your non-plugin stuff after this line 

make sure you're doing that. 

Once you set that then go to CL and just $ vim 

once vim opens run :PluginInstall 

:q vim and start a new vim session $ vim 

once vim opens run :IndentGuidesEnabled 

then bask in the glory of indent guides xD 

Let me know if this helps. GL!!

**Comment by yukie-** [comment]
hey spawnazzo, sorry if that above comment seemed a little disjointed, wrote it on mobile >.> 

But I was wondering if you got it going? I hope so..

**Comment by spawnazzo** [comment]
Ok :+1:  now it works still wondering why was not working in my other setup. 
Thanks for helping anyway

**Comment by yukie-** [comment]
that's awesome :)
