### ISSUE TITLE
[Feature request] Keep highlighting in empty lines

### ISSUE THREAD

**Issue by fvisin** [nathanaelkane/vim-indent-guides#97]
Sometimes I add empty lines in my code to make it more readable,e.g.:
``` python
def example(self, x):
*   if some_condition:
*   *   max_el = 0

*   *   for el in x:
*   *   *   another_var = 0

*   *   *   if el > max_el:
*   *   *   *   max_el = el
```
If the lines surrounding the empty code have the same indentation level, I'd like the empty line to be highlighted too.
``` python
def example(self, x):
*   if some_condition:
*   *   max_el = 0
*   *
*   *   for el in x:
*   *   *   another_var = 0
*   *   *
*   *   *   if el > max_el:
*   *   *   *   max_el = el
```

**Comment by nathanaelkane** [comment]
This is an I'm afraid this is not possible, see issue #23 for details.

**Comment by fvisin** [comment]
Isn't it feasible to fill the empty line with spaces (so that you can highlight them) and delete the extra spaces when the file is saved?

**Comment by nathanaelkane** [comment]
@fvisin That could work, and I've considered it before but there's a few reasons I don't want to implement it:

- I don't like littering other peoples code with unneeded whitespace, even if temporarily.
- You'd have to remove all trailing whitespace on save, even if it wasn't added by this plugin (which I don't like). The alternative is to track and remove only the whitespace added by the plugin, and I think that'd be extremely hard.

Also, I see no reason why this functionality needs to be coupled with this plugin, it could be a standalone plugin intended to be used with this and other similar plugins.
