### ISSUE TITLE
Disable indent guides for specific buffers locally

### ISSUE THREAD

**Issue by unclechu** [nathanaelkane/vim-indent-guides#98]
Can I disable indent guides for specific buffers locally? I want to write some `autocmd` by `FileType` and disable indent guides for specific languages, can I do it?

**Comment by nathanaelkane** [comment]
Would `let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']` be suitable?

**Comment by unclechu** [comment]
@nathanaelkane thanks a lot, it works for me!
