### ISSUE TITLE
Plugin "eating" some parts of the code of Laravel Blade with leading spaces.

### ISSUE THREAD

**Issue by brunoti** [nathanaelkane/vim-indent-guides#99]
**The code without leading spaces:**
![screenshot 2015-10-06 16 13 10](https://cloud.githubusercontent.com/assets/6011421/10319614/89657472-6c45-11e5-827b-1d451135003f.png)

**The code with leading spaces:**
![screenshot 2015-10-06 16 12 09](https://cloud.githubusercontent.com/assets/6011421/10319645/ac0e9a76-6c45-11e5-9e62-f108c0285113.png)

Is this a bug or is my mistake?

**Comment by nathanaelkane** [comment]
I can't see Vim Indent Guides being used in either screenshot, are you sure it's what causing your problem? Does disabling the plugin fix your issue?

**Comment by brunoti** [comment]
Man... I think i make this issue in the wrong plugin repository! 

I'm sorry!

**Comment by iamrahulroy** [comment]
@nathanaelkane Is it possible to add [leading spaces](https://camo.githubusercontent.com/704f183f97df23ba5c21dc238b81069644d5cd7c/687474703a2f2f692e696d6775722e636f6d2f303741747272732e706e67) with vim indent guides? This can be achieved via  [indentLine](https://github.com/Yggdroot/indentLine) plugin.

**Comment by nathanaelkane** [comment]
@iamrahulroy I'm not sure what you mean by "add leading spaces"? Can you please elaborate.

**Comment by iamrahulroy** [comment]
@nathanaelkane I liked screenshot above and I'm linking it again https://camo.githubusercontent.com/73a4b5e80ee0364c8f5e7e2b8f1af309c79ce739/687474703a2f2f692e696d6775722e636f6d2f744c596b6237392e706e67 

By leading spaces, I mean soft tabs to be represented by dots. Is it possible to do this with `vim-indent-guides`? If not I'll go ahead and install `indentLine` plugin.

**Comment by nathanaelkane** [comment]
@iamrahulroy Thanks for clarifying. To answer your question, no that is not a feature of this plugin. This plugin is for simply for displaying indent guide lines.

I use `set list` (with `listchars` configured appropriately) when I want to see leading spaces. See http://vimcasts.org/episodes/show-invisibles/ for more details.

I'm going to lock this conversation because we've hijacked a different issue.
